### ISSUE TITLE
No enum constant NoteCommentAction.HIDDEN 2

### ISSUE THREAD

**Issue by caillou15** [ubipo/osmfocus#43] opened 2022-07-03 09:27 UTC
When I open the app, this error message is shown after 1 second.

No enum constant net.pfiers.osmfocus.service.osm.NoteCommentAction.HIDDEN

**Comment by ubipo** [comment] 2022-07-03 09:32
Hey Caillou!

This is a duplicate of #38, which I'll get to when I find the time.

As a workaround you can clear the app data and not zoom into the area where this error occured again.

Sorry for the inconvenience!

**Closed** 2022-07-03 09:32 UTC
Labels: duplicate
