### ISSUE TITLE
Crash: No parameter #5 uid provided for OsmApiNode

### ISSUE THREAD

**Issue by tuukka** [ubipo/osmfocus#18] opened 2021-05-03 09:20 UTC
```
An error occurred

The app couldn't recover from the following error:

Unable to instantiate OsmApiNode:

Parameter id: expected kotlin.Long but received java.lang.Long (value: 34181010)

Parameter version: expected kotlin.Int but received java.lang.Integer (value: 1)

Parameter changeset: expected kotlin.Long but received java.lang.Long (value: 210005) 

No argument provided for a required parameter: parameter #5 uid of fun <init>(net.pfiers.osmfocus.service.osm.ElementType, kotlin.Long, kotlin.Int, kotlin.Long, `j$`.time.Instant, kotlin.Int, kotlin.String, kotlin.Double, kotlin.Double, kotlin.collections.Map<kotlin.String, kotlin.String>?): net.pfiers.osmfocus.service.osmapi.OsmApiNode

No argument provided for a required parameter: parameter #5 uid of fun <init>(net.pfiers.osmfocus.service.osm.ElementType, kotlin.Long, kotlin.Int, kotlin.Long, `j$`.time.Instant,
```
![Screenshot_20210502-173428](https://user-images.githubusercontent.com/76985/116860177-d8fbdd00-ac09-11eb-95ab-8885b55cd964.jpg)

**Comment by ubipo** [comment] 2021-10-31 22:42
I can't reproduce this in version 1.2.0. Closing for now.

**Closed by ubipo** 2021-10-31 22:42 UTC
