### ISSUE TITLE
Unhandled exception: java.nio.charset.CharsetICU[UTF-8]

### ISSUE THREAD

**Issue by deevroman** [ubipo/osmfocus#33] opened 2021-11-16 18:34 UTC
##  Exception details
Message: `java.nio.charset.CharsetICU[UTF-8]`
         
##  What happened / what actions did you take before the bug occurred?
Open info about [w36882918](https://www.openstreetmap.org/way/36882918)

##  Comments
-- Fill here if necessary --

## Stack trace
```
java.nio.charset.IllegalCharsetNameException: java.nio.charset.CharsetICU[UTF-8]
	at java.nio.charset.Charset.checkCharsetName(Charset.java:201)
	at java.nio.charset.Charset.forName(Charset.java:295)
	at java.net.URLEncoder.encode(URLEncoder.java:57)
	at net.pfiers.osmfocus.view.fragments.ElementDetailsFragment$onCreateView$tagsListAdapter$1$1.invokeSuspend(ElementDetailsFragment.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

```

## System / app info
```
App version: 1.2.3-fdroid
App version code: 123
App build type: release
Android version: 22
Device name: samsung SM-J120F
```

**Comment by ubipo** [comment] 2022-04-08 16:06
Fixed, duplicate of #30

**Closed by ubipo** 2022-04-08 16:06 UTC
