### ISSUE TITLE
Unhandled exception: Incorrect resolution sequence for Java constructor public constructor i() defined in m6.i[c@5e6cf44] (x3.j: class m6.i)

### ISSUE THREAD

**Issue by amandasaurus** [ubipo/osmfocus#24] opened 2021-10-24 13:06 UTC
##  Exception details
Message: `Incorrect resolution sequence for Java constructor public constructor i() defined in m6.i[c@5e6cf44] (x3.j: class m6.i)`
         
##  What happened / what actions did you take before the bug occurred?
-- Please fill here --

##  Comments
-- Fill here if necessary --

## Stack trace
```
n3.z: Incorrect resolution sequence for Java constructor public constructor i() defined in m6.i[c@5e6cf44] (x3.j: class m6.i)
	at n3.f0.g(RuntimeTypeMapper.kt:23)
	at n3.k.<init>(KFunctionImpl.kt:8)
	at n3.g$a$e.a(KClassImpl.kt:5)
	at n3.g$a$e.l(KClassImpl.kt:1)
	at n3.b0$a.c(ReflectProperties.java:4)
	at n3.b0$c.b(ReflectProperties.java:1)
	at n3.g$a.k(Unknown Source:7)
	at n3.g.m(KClassImpl.kt:1)
	at k1.l.h(JsonObjectConverter.kt:14)
	at k1.l.d(JsonObjectConverter.kt:3)
	at k1.d.h(DefaultConverter.kt:38)
	at k1.d.a(DefaultConverter.kt:17)
	at k1.p.g(Klaxon.kt:9)
	at m6.b.c(api.kt:22)
	at m6.b$b.i(Unknown Source:16)
	at w2.a.o(ContinuationImpl.kt:3)
	at u5.a1.run(DispatchedTask.kt:22)
	at kotlinx.coroutines.scheduling.a.y(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.a$c.c(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.m(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.a$c.run(CoroutineScheduler.kt:1)

```

## System / app info
```
App version: 1.1.2-fdroid
App version code: 112
App build type: release
Android version: 29
Device name: Fairphone FP3
```

**Comment by ubipo** [comment] 2021-10-31 19:31
Duplicate of  #23. Fixed in 00dd435, will be released with v1.2.0.

**Closed by ubipo** 2021-10-31 19:31 UTC
